services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    container_name: bot
    restart: always
    environment:
      - PYTHONPATH=/app/src
      - BACKEND_SERVER_URL=http://django_app:8000/telegram-auth/
    env_file:
      - .env

  django_app:
    container_name: django_app
    build:
      context: .
      dockerfile: docker/django_app/Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./django_app/src:/app/src
    environment:
      - DJANGO_ENV=dev
      - PYTHONPATH=/app/src
    env_file:
      - .env
    restart: always
    command: [ "/app/entrypoint.sh" ]
